apiVersion: v1
kind: PersistentVolume
metadata:
  name: workshop-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
   path: /pv
---
apiVersion: v1
kind: Pod
metadata:
  name: workshop-pvpod
spec:
  containers:
  - name: container
    image: redis
    volumeMounts:
    - name: workshop-pvpod
      mountPath: /mount1
  volumes:
  - name : workshop-pvpod
    persistentVolumeClaim:
      claimName: pvc
---
apiVersion: v1
kind : PersistentVolumeClaim
metadata:
  name: pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
