apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pro1-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      name: pro1-rs
      labels:
        app: busybox
    spec:
      containers:
      - name: pro1-rs
        image: busybox
