apiVersion: v1
kind: Namespace
metadata:
  name: alpha
---
apiVersion: v1
kind: Namespace
metadata:
  name: beta
---
apiVersion: v1
kind: Namespace
metadata:
  name: gamma
---
apiVersion: v1
kind: Namespace
metadata:
  name: workshop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-dp
  namespace: workshop
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: workshop-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: red
  namespace: gamma
spec:
  containers:
  - name: red
    image: nginx
    ports:
    - containerPort: 80
